# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_design/graph_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReadLoggerDataWindow(object):
    def setupUi(self, ReadLoggerDataWindow):
        ReadLoggerDataWindow.setObjectName("ReadLoggerDataWindow")
        ReadLoggerDataWindow.resize(921, 597)
        ReadLoggerDataWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(ReadLoggerDataWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.comboBox_temp_unit = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_temp_unit.sizePolicy().hasHeightForWidth())
        self.comboBox_temp_unit.setSizePolicy(sizePolicy)
        self.comboBox_temp_unit.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_temp_unit.setStyleSheet("selection-color: rgb(0,0,0);")
        self.comboBox_temp_unit.setObjectName("comboBox_temp_unit")
        self.comboBox_temp_unit.addItem("")
        self.comboBox_temp_unit.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_temp_unit)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.MplWidget = MplWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MplWidget.sizePolicy().hasHeightForWidth())
        self.MplWidget.setSizePolicy(sizePolicy)
        self.MplWidget.setMinimumSize(QtCore.QSize(880, 374))
        self.MplWidget.setStyleSheet("background-color: rgb(173, 127, 168);")
        self.MplWidget.setObjectName("MplWidget")
        self.verticalLayout_2.addWidget(self.MplWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.graph_start_dt = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph_start_dt.sizePolicy().hasHeightForWidth())
        self.graph_start_dt.setSizePolicy(sizePolicy)
        self.graph_start_dt.setMinimumSize(QtCore.QSize(0, 30))
        self.graph_start_dt.setObjectName("graph_start_dt")
        self.verticalLayout.addWidget(self.graph_start_dt)
        self.graph_end_dt = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph_end_dt.sizePolicy().hasHeightForWidth())
        self.graph_end_dt.setSizePolicy(sizePolicy)
        self.graph_end_dt.setMinimumSize(QtCore.QSize(0, 30))
        self.graph_end_dt.setObjectName("graph_end_dt")
        self.verticalLayout.addWidget(self.graph_end_dt)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(678, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_generate_report = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_generate_report.sizePolicy().hasHeightForWidth())
        self.btn_generate_report.setSizePolicy(sizePolicy)
        self.btn_generate_report.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_generate_report.setObjectName("btn_generate_report")
        self.horizontalLayout.addWidget(self.btn_generate_report)
        spacerItem1 = QtWidgets.QSpacerItem(58, 18, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        ReadLoggerDataWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ReadLoggerDataWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 921, 22))
        self.menubar.setObjectName("menubar")
        ReadLoggerDataWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ReadLoggerDataWindow)
        self.statusbar.setObjectName("statusbar")
        ReadLoggerDataWindow.setStatusBar(self.statusbar)
        self.label.setBuddy(self.comboBox_temp_unit)

        self.retranslateUi(ReadLoggerDataWindow)
        QtCore.QMetaObject.connectSlotsByName(ReadLoggerDataWindow)

    def retranslateUi(self, ReadLoggerDataWindow):
        _translate = QtCore.QCoreApplication.translate
        ReadLoggerDataWindow.setWindowTitle(_translate("ReadLoggerDataWindow", "MainWindow"))
        self.label.setText(_translate("ReadLoggerDataWindow", "Temperature Unit : "))
        self.comboBox_temp_unit.setItemText(0, _translate("ReadLoggerDataWindow", "Kelvin"))
        self.comboBox_temp_unit.setItemText(1, _translate("ReadLoggerDataWindow", "Celsius"))
        self.graph_start_dt.setText(_translate("ReadLoggerDataWindow", "End :"))
        self.graph_end_dt.setText(_translate("ReadLoggerDataWindow", "Start :"))
        self.btn_generate_report.setText(_translate("ReadLoggerDataWindow", "Generate Report"))
from mplwidget import MplWidget
