# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(684, 866)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 20, 641, 201))
        self.frame.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_battery_level_low_signal = QtWidgets.QLabel(self.frame)
        self.label_battery_level_low_signal.setGeometry(QtCore.QRect(230, 120, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_battery_level_low_signal.setFont(font)
        self.label_battery_level_low_signal.setText("")
        self.label_battery_level_low_signal.setObjectName("label_battery_level_low_signal")
        self.label_device_type = QtWidgets.QLabel(self.frame)
        self.label_device_type.setGeometry(QtCore.QRect(150, 90, 431, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_device_type.setFont(font)
        self.label_device_type.setText("")
        self.label_device_type.setObjectName("label_device_type")
        self.label_title_battery_level = QtWidgets.QLabel(self.frame)
        self.label_title_battery_level.setGeometry(QtCore.QRect(20, 120, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_title_battery_level.setFont(font)
        self.label_title_battery_level.setObjectName("label_title_battery_level")
        self.label_title_device_type = QtWidgets.QLabel(self.frame)
        self.label_title_device_type.setGeometry(QtCore.QRect(20, 89, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_title_device_type.setFont(font)
        self.label_title_device_type.setObjectName("label_title_device_type")
        self.lineEdit_device_name = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_device_name.setGeometry(QtCore.QRect(150, 150, 211, 31))
        self.lineEdit_device_name.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_device_name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_device_name.setObjectName("lineEdit_device_name")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(20, 150, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.btn_device_rename = QtWidgets.QPushButton(self.frame)
        self.btn_device_rename.setGeometry(QtCore.QRect(400, 150, 181, 31))
        self.btn_device_rename.setObjectName("btn_device_rename")
        self.label_title_device_information_2 = QtWidgets.QLabel(self.frame)
        self.label_title_device_information_2.setGeometry(QtCore.QRect(20, 10, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_title_device_information_2.setFont(font)
        self.label_title_device_information_2.setObjectName("label_title_device_information_2")
        self.label_device_id = QtWidgets.QLabel(self.frame)
        self.label_device_id.setGeometry(QtCore.QRect(220, 10, 381, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_device_id.setFont(font)
        self.label_device_id.setText("")
        self.label_device_id.setObjectName("label_device_id")
        self.btn_erase_data = QtWidgets.QPushButton(self.frame)
        self.btn_erase_data.setGeometry(QtCore.QRect(230, 40, 181, 31))
        self.btn_erase_data.setObjectName("btn_erase_data")
        self.label_title_device_id_2 = QtWidgets.QLabel(self.frame)
        self.label_title_device_id_2.setGeometry(QtCore.QRect(20, 39, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_title_device_id_2.setFont(font)
        self.label_title_device_id_2.setObjectName("label_title_device_id_2")
        self.label_battery_level = QtWidgets.QLabel(self.frame)
        self.label_battery_level.setGeometry(QtCore.QRect(160, 120, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_battery_level.setFont(font)
        self.label_battery_level.setText("")
        self.label_battery_level.setObjectName("label_battery_level")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(20, 240, 641, 131))
        self.frame_2.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_device_time = QtWidgets.QLabel(self.frame_2)
        self.label_device_time.setGeometry(QtCore.QRect(150, 60, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_device_time.setFont(font)
        self.label_device_time.setText("")
        self.label_device_time.setObjectName("label_device_time")
        self.label_d_id_6 = QtWidgets.QLabel(self.frame_2)
        self.label_d_id_6.setGeometry(QtCore.QRect(20, 60, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_d_id_6.setFont(font)
        self.label_d_id_6.setObjectName("label_d_id_6")
        self.label_d_id_7 = QtWidgets.QLabel(self.frame_2)
        self.label_d_id_7.setGeometry(QtCore.QRect(20, 90, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_d_id_7.setFont(font)
        self.label_d_id_7.setObjectName("label_d_id_7")
        self.label_system_time = QtWidgets.QLabel(self.frame_2)
        self.label_system_time.setGeometry(QtCore.QRect(150, 90, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_system_time.setFont(font)
        self.label_system_time.setText("")
        self.label_system_time.setObjectName("label_system_time")
        self.btn_sync_device_system_time = QtWidgets.QPushButton(self.frame_2)
        self.btn_sync_device_system_time.setGeometry(QtCore.QRect(400, 60, 181, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_sync_device_system_time.sizePolicy().hasHeightForWidth())
        self.btn_sync_device_system_time.setSizePolicy(sizePolicy)
        self.btn_sync_device_system_time.setObjectName("btn_sync_device_system_time")
        self.checkBox_dst = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_dst.setGeometry(QtCore.QRect(10, 20, 171, 23))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.checkBox_dst.setFont(font)
        self.checkBox_dst.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_dst.setObjectName("checkBox_dst")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(20, 390, 641, 201))
        self.frame_3.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 51, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(10, 160, 51, 21))
        self.label_5.setObjectName("label_5")
        self.dateTimeEdit_logging_start = QtWidgets.QDateTimeEdit(self.frame_3)
        self.dateTimeEdit_logging_start.setGeometry(QtCore.QRect(190, 120, 161, 26))
        self.dateTimeEdit_logging_start.setObjectName("dateTimeEdit_logging_start")
        self.btn_set_start_stop_option = QtWidgets.QPushButton(self.frame_3)
        self.btn_set_start_stop_option.setGeometry(QtCore.QRect(400, 130, 181, 41))
        self.btn_set_start_stop_option.setObjectName("btn_set_start_stop_option")
        self.dateTimeEdit_logging_stop = QtWidgets.QDateTimeEdit(self.frame_3)
        self.dateTimeEdit_logging_stop.setGeometry(QtCore.QRect(190, 160, 161, 25))
        self.dateTimeEdit_logging_stop.setObjectName("dateTimeEdit_logging_stop")
        self.comboBox_logging_start = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_logging_start.setGeometry(QtCore.QRect(60, 120, 121, 25))
        self.comboBox_logging_start.setStyleSheet("selection-color: rgb(0, 0, 0);")
        self.comboBox_logging_start.setObjectName("comboBox_logging_start")
        self.comboBox_logging_start.addItem("")
        self.comboBox_logging_start.addItem("")
        self.comboBox_logging_stop = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_logging_stop.setGeometry(QtCore.QRect(60, 160, 121, 25))
        self.comboBox_logging_stop.setStyleSheet("selection-color: rgb(0, 0, 0);")
        self.comboBox_logging_stop.setObjectName("comboBox_logging_stop")
        self.comboBox_logging_stop.addItem("")
        self.comboBox_logging_stop.addItem("")
        self.btn_set_logging_interval = QtWidgets.QPushButton(self.frame_3)
        self.btn_set_logging_interval.setGeometry(QtCore.QRect(400, 50, 181, 41))
        self.btn_set_logging_interval.setObjectName("btn_set_logging_interval")
        self.label_d_id_5 = QtWidgets.QLabel(self.frame_3)
        self.label_d_id_5.setGeometry(QtCore.QRect(10, 50, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_d_id_5.setFont(font)
        self.label_d_id_5.setObjectName("label_d_id_5")
        self.label_d_id_4 = QtWidgets.QLabel(self.frame_3)
        self.label_d_id_4.setGeometry(QtCore.QRect(10, 80, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_d_id_4.setFont(font)
        self.label_d_id_4.setObjectName("label_d_id_4")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(250, 70, 81, 17))
        self.label_2.setObjectName("label_2")
        self.lineEdit_logging_interval = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_logging_interval.setGeometry(QtCore.QRect(170, 50, 71, 51))
        self.lineEdit_logging_interval.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_logging_interval.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_logging_interval.setText("")
        self.lineEdit_logging_interval.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_logging_interval.setObjectName("lineEdit_logging_interval")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(20, 610, 641, 131))
        self.frame_4.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.btn_set_alarm = QtWidgets.QPushButton(self.frame_4)
        self.btn_set_alarm.setGeometry(QtCore.QRect(400, 60, 181, 31))
        self.btn_set_alarm.setObjectName("btn_set_alarm")
        self.label_temp_h = QtWidgets.QLabel(self.frame_4)
        self.label_temp_h.setGeometry(QtCore.QRect(10, 50, 191, 31))
        self.label_temp_h.setObjectName("label_temp_h")
        self.label_temp_l = QtWidgets.QLabel(self.frame_4)
        self.label_temp_l.setGeometry(QtCore.QRect(10, 90, 171, 31))
        self.label_temp_l.setObjectName("label_temp_l")
        self.lineEdit_high_temp = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_high_temp.setGeometry(QtCore.QRect(200, 50, 61, 31))
        self.lineEdit_high_temp.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_high_temp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_high_temp.setObjectName("lineEdit_high_temp")
        self.lineEdit_low_temp = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_low_temp.setGeometry(QtCore.QRect(200, 90, 61, 31))
        self.lineEdit_low_temp.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_low_temp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_low_temp.setObjectName("lineEdit_low_temp")
        self.label_temp_h_d = QtWidgets.QLabel(self.frame_4)
        self.label_temp_h_d.setGeometry(QtCore.QRect(270, 60, 21, 17))
        self.label_temp_h_d.setObjectName("label_temp_h_d")
        self.label_temp_l_d = QtWidgets.QLabel(self.frame_4)
        self.label_temp_l_d.setGeometry(QtCore.QRect(270, 100, 21, 17))
        self.label_temp_l_d.setObjectName("label_temp_l_d")
        self.checkBox_temp_alarm_status = QtWidgets.QCheckBox(self.frame_4)
        self.checkBox_temp_alarm_status.setGeometry(QtCore.QRect(10, 10, 241, 23))
        self.checkBox_temp_alarm_status.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_temp_alarm_status.setObjectName("checkBox_temp_alarm_status")
        self.btn_read_logger_data = QtWidgets.QPushButton(self.centralwidget)
        self.btn_read_logger_data.setGeometry(QtCore.QRect(200, 770, 291, 41))
        self.btn_read_logger_data.setObjectName("btn_read_logger_data")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 684, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CS Reader"))
        self.label_title_battery_level.setText(_translate("MainWindow", "Battery Voltage : "))
        self.label_title_device_type.setText(_translate("MainWindow", "Device Type : "))
        self.label_11.setText(_translate("MainWindow", "Device Name : "))
        self.btn_device_rename.setText(_translate("MainWindow", "Rename"))
        self.label_title_device_information_2.setText(_translate("MainWindow", "Connected Device :"))
        self.btn_erase_data.setText(_translate("MainWindow", "Erase"))
        self.label_title_device_id_2.setText(_translate("MainWindow", "Erase all stored data : "))
        self.label_d_id_6.setText(_translate("MainWindow", "Device Time   :"))
        self.label_d_id_7.setText(_translate("MainWindow", "System Time  :"))
        self.btn_sync_device_system_time.setText(_translate("MainWindow", "Match Device Time To \n"
"System Time"))
        self.checkBox_dst.setText(_translate("MainWindow", "Daylight saving :     "))
        self.label_3.setText(_translate("MainWindow", "Logging Options :"))
        self.label_4.setText(_translate("MainWindow", "Start :"))
        self.label_5.setText(_translate("MainWindow", "Stop :"))
        self.dateTimeEdit_logging_start.setDisplayFormat(_translate("MainWindow", "d/M/yyyy hh:mm:ss"))
        self.btn_set_start_stop_option.setText(_translate("MainWindow", "Set Start/Stop Option"))
        self.dateTimeEdit_logging_stop.setDisplayFormat(_translate("MainWindow", "d/M/yyyy hh:mm:ss"))
        self.comboBox_logging_start.setItemText(0, _translate("MainWindow", "Button Press"))
        self.comboBox_logging_start.setItemText(1, _translate("MainWindow", "Time"))
        self.comboBox_logging_stop.setItemText(0, _translate("MainWindow", "Button Press"))
        self.comboBox_logging_stop.setItemText(1, _translate("MainWindow", "Time"))
        self.btn_set_logging_interval.setText(_translate("MainWindow", "Set Logging Interval"))
        self.label_d_id_5.setText(_translate("MainWindow", "Interval : "))
        self.label_d_id_4.setText(_translate("MainWindow", "(range : 1 to 1440)"))
        self.label_2.setText(_translate("MainWindow", "minutes(s)"))
        self.btn_set_alarm.setText(_translate("MainWindow", "Set Alarm"))
        self.label_temp_h.setText(_translate("MainWindow", "High Temperature Value :"))
        self.label_temp_l.setText(_translate("MainWindow", "Low temperature Value : "))
        self.label_temp_h_d.setText(_translate("MainWindow", "c"))
        self.label_temp_l_d.setText(_translate("MainWindow", "c"))
        self.checkBox_temp_alarm_status.setText(_translate("MainWindow", "Temperature Alarm Status:           "))
        self.btn_read_logger_data.setText(_translate("MainWindow", "Read Logged Data"))
